### PR TITLE
Make XConn::atom_prop() work for arbitrary atoms

### LINKED ISSUE #112: Argument of XConn::atom_prop() should be Atom or the xcb implementation be changed
[Sorry, but this time I will completely ignore the issue template; feel free to tell me not to do that again]

Let's look at this code: https://github.com/sminez/penrose/blob/69912708f7982b7d6a61b9fa549040fb4c3625fb/src/xcb/xconn.rs#L330-L331
This uses `Atom::from_str(name)?` on the argument. Thus, this will always fail with non-`Atom` arguments. That's unexpected and feels like a bug to me. I wanted to just fix this, but since this function doesn't seem to have any callers, I decided to report this as an issue instead.

Options that I see:
- Just remove this function (but it exists so that people can use it from their config, I guess)
- Change the argument type from `&str` to `Atom`
- Change the implementation to work similarly to `get_str_prop()` so that it supports arbitrary atom names

### PR DESCRIPTION
**Pull request by psychon**
Before this commit XcbConnection::atom_prop() used Atom::from_str(name)?
on its argument. Thus, it only worked for the predefined atoms. This
commit changes it to also work for arbitrary atoms. To make this work,
the XcbApi trait had to be changed accordingly.

Fixes: https://github.com/sminez/penrose/issues/112
Signed-off-by: Uli Schlachter <psychon@znc.in>

### CODE REVIEW

**Comment by psychon** [comment]
I don't know what dangerjs is / does, but I fail to understand that check. I would guess that it just does not work for PRs...?

File: src/xcb/xconn.rs [hunk 1]
```diff
@@ -70,7 +70,7 @@ impl XcbConnection {
     }
 
     fn window_has_type_in(&self, id: WinId, win_types: &[u32]) -> bool {
-        if let Ok(atom) = self.api.get_atom_prop(id, Atom::NetWmWindowType) {
+        if let Ok(atom) = self.api.get_atom_prop(id, "_NET_WM_WINDOW_TYPE") {
```
Comment (sminez) [inline src/xcb/xconn.rs]: can this be changed to `Atom::NetWmWindowType.as_ref()` like the rest of the code base please: I want to avoid any hard coded `&str` literals for known atom names.

**Review by sminez — CHANGES_REQUESTED** [review]
Looks like your branch needs rebasing from develop as well

**Comment by sminez** [comment]
[TIL](https://github.com/actions/first-interaction/issues/10) that github actions downgrades the scope of the credentials given to your action when running from a fork :disappointed: 

`danger.js` runs some additional checks on the PR and then _should_ add labels to the PR based on what parts of the code base are being modified. I'll have to look into what (if anything) can be done for PRs raised from forks rather than a branch in the repo: for PR branches `danger` works just fine.

File: src/xcb/xconn.rs (hunk 1 above)
Comment (psychon) [reply src/xcb/xconn.rs]: Done. I amended that into the commit.

Yeah, I was not totally happy with that solution either, but obviously didn't think enough about it. Sorry.

Comment (sminez) [reply src/xcb/xconn.rs]: Thanks! If you can rebase off of current develop I'll get this merged :+1:

Comment (psychon) [reply src/xcb/xconn.rs]: Done

**Review by sminez — APPROVED** [review]

**Comment by sminez** [comment]
Oh good! The PR bot works properly now for forks as well :tada:
