### PR TITLE
Fix for layout not being applied when follow_focus is used

### LINKED ISSUE #211: Cycling clients breaks follow_focus layouts
### Describe the bug
Cycling clients does not trigger a call to `apply_layout` when `LayoutConf.follow_focus = true`.

### To reproduce
Use the following minimal penrose config:

##### Cargo.toml
```toml
[package]
name = "penrose-issue-test"
version = "0.1.0"
edition = "2021"

[dependencies]
penrose = "0.2.1"
```

##### src/main.rs
```rust
#[macro_use]
extern crate penrose;

use penrose::{
    core::{
        config::Config,
        layout::{monocle, side_stack, Layout, LayoutConf},
        ring::Direction::{Backward, Forward},
    },
    logging_error_handler,
    xcb::new_xcb_backed_window_manager,
    PenroseError,
};

fn main() -> penrose::Result<()> {
    let layout = vec![
        Layout::new(
            "mono",
            LayoutConf {
                floating: false,
                gapless: true,
                follow_focus: true,
                allow_wrapping: true,
            },
            monocle,
            1,
            0.6,
        ),
        Layout::new("stact", LayoutConf::default(), side_stack, 1, 0.6),
    ];

    let config = Config::default()
        .builder()
        .layouts(layout)
        .build()
        .map_err(|s| PenroseError::Raw(s))?;

    let key_bindings = gen_keybindings! {
        "M-S-e" => run_internal!(exit);

        // replace "alacritty" with any terminal emulator
        "M-Return" => run_external!("alacritty");
        "M-w" => run_internal!(kill_client);

        "M-space" => run_internal!(cycle_layout, Forward);

        "M-j" => run_internal!(cycle_client, Forward);
        "M-k" => run_internal!(cycle_client, Backward);
    };

    let mut wm = new_xcb_backed_window_manager(config, vec![], logging_error_handler())?;
    wm.grab_keys_and_run(key_bindings, map! {})
}
```

### Expected behavior
Cycling clients will unmap all unfocused clients and map the new focused client when using the 
builtin `monocle` layout. Instead, the client that was focused before the `cycle_client` event 
will remain the only client that is mapped despite not being the focused client from the window 
manager's perspective (the border color reflects this).

### Versions & OS details
Tested on Arch Linux

### Additional thoughts
I think I have discovered the cause and will make a pull request with the fix.

### PR DESCRIPTION
**Pull request by niloco**
Fixes #211, let me know if there should be more behavior tests added.

### CODE REVIEW

File: src/core/manager/mod.rs [hunk 1]
```diff
@@ -1681,6 +1681,54 @@ mod tests {
...
+        let mut wm = WindowManager::new(conf, conn, vec![], logging_error_handler());
+        wm.init().unwrap();
+        add_n_clients(&mut wm, 3, 0);
+        wm.focus_workspace(&Selector::Index(1)).unwrap();
+        add_n_clients(&mut wm, 3, 30);
+        wm.focus_workspace(&Selector::Index(0)).unwrap();
+        wm.conn.clear();
+        wm.cycle_client(Direction::Forward).unwrap();
+
+        let should_be_true = wm.conn.calls().iter().any(|c| c.0 == *"position_client");
```
Comment (sminez) [inline src/core/manager/mod.rs]: Can these assertions be rewritten without dereferencing the `&str` here? I'm sure it works but it's pretty funky...

I'd expect this to work?
```rust
assert!(wm.conn.calls().iter().any(|(method, _)| method == "position_client"))
```

Or alternatively, this sort of thing with the `RecordingXConn` is actually quite useful so it might be worthwile making it a method:
```rust
// in src/__test_helpers.rs
impl RecordingXConn {
    ...

    pub fn was_called(&self, method: &str) -> bool {
        self.calls().iter().any(|(m, _)| m == method)
    }

    pub fn was_not_called(&self, method: &str) -> bool {
        self.calls().iter().all(|(m, _)| m != method)
    }
}

// in your test
assert!(wm.conn.was_called("position_client"))
```

File: src/core/manager/mod.rs [hunk 2]
```diff
@@ -1681,6 +1681,54 @@ mod tests {
...
+        // shouldn't trigger layout when re-focusing same client
+        wm.focus_client(&Selector::WinId(0)).unwrap();
+        let should_be_false = wm.conn.calls().iter().any(|c| c.0 == *"position_client");
+        wm.conn.clear();
+
+        // focusing any other client should trigger layout stuff
+        wm.focus_client(&Selector::WinId(1)).unwrap();
+        let should_be_true = wm.conn.calls().iter().any(|c| c.0 == *"position_client");
+
+        assert!(!should_be_false);
```
Comment (sminez) [inline src/core/manager/mod.rs]: The naming and negation is a bit confusing here. Can you inline these assertions please? (See the example given above)

**Review by sminez — CHANGES_REQUESTED** [review]
Thank you for looking into this one. The approach itself looks good but I have a few requests for changes with the tests, let me know if my comments don't make sense.

**Comment by niloco** [comment]
Implemented your suggested changes, tests are more readable as a result.

**Review by sminez — APPROVED** [review]
Fab! Thank you for this

**Comment by niloco** [comment]
Happy to help, I've been enjoying my time with penrose thus far.
